<?php

rex_sql_table::get(rex::getTable('search_source'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('name', 'varchar(255)'))
    ->ensureColumn(new rex_sql_column('type_key', 'varchar(64)'))
    ->ensureColumn(new rex_sql_column('config', 'json', true))
    ->ensureColumn(new rex_sql_column('status', 'tinyint(1)', false, '1'))
    ->ensureColumn(new rex_sql_column('last_indexed_at', 'datetime', true))
    ->ensureColumn(new rex_sql_column('item_count', 'int(11)', false, '0'))
    ->ensureGlobalColumns()
    ->ensureIndex(new rex_sql_index('type_key', ['type_key']))
    ->removeColumn('priority')
    ->ensure();

rex_sql_table::get(rex::getTable('search_index'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('source_id', 'int(11)'))
    ->ensureColumn(new rex_sql_column('namespace', 'varchar(64)'))
    ->ensureColumn(new rex_sql_column('type', 'varchar(191)'))
    ->ensureColumn(new rex_sql_column('item_id', 'varchar(191)'))
    ->ensureColumn(new rex_sql_column('index_id', 'varchar(191)'))
    ->ensureColumn(new rex_sql_column('title', 'varchar(255)', false, ''))
    ->ensureColumn(new rex_sql_column('content', 'mediumtext', true))
    ->ensureColumn(new rex_sql_column('url', 'varchar(1024)', false, ''))
    ->ensureColumn(new rex_sql_column('clang_id', 'int(11)', true))
    ->ensureColumn(new rex_sql_column('meta', 'json', true))
    ->ensureColumn(new rex_sql_column('content_hash', 'char(40)', false, ''))
    ->ensureColumn(new rex_sql_column('updated_at', 'datetime', true))
    ->ensureColumn(new rex_sql_column('indexed_at', 'datetime'))
    ->ensureIndex(new rex_sql_index('source_index', ['source_id', 'index_id'], rex_sql_index::UNIQUE))
    ->ensureIndex(new rex_sql_index('source_item', ['source_id', 'item_id']))
    ->ensureIndex(new rex_sql_index('namespace_type', ['namespace', 'type']))
    ->ensureIndex(new rex_sql_index('fulltext_content', ['title', 'content'], rex_sql_index::FULLTEXT))
    ->ensure();
